# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
#features-- CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
y = dataset.iloc[:, -1].values
#target(binary)-- Exited (yes=1, no=0)

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data-- no missing data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
#label encoding 'gender' column

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
#one-hot endoded 'Geography' column

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()
#Sequential class belongs to models module. Models module belongs to keras library of tensorflow package
#Sequential class allows to build a layered neural network 

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#add() function adds a layer within a neural network
#layers are created as objects of Dense class of layers module from keras library of tensorflow package 
#all input layer neurons are fully connected to all first hidden layer neurons-- Dense() class 
#units is the number of neurons in first hidden layer , input layer neurons will automatically be equal to number of features

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
#all first hidden layer neurons are fully connected to all second hidden layer neurons-- Dense() class 

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
#for output layer, always have no activation function(continuous target output) or sortMax(classification between more than 2 categories)
#binary classification target --> sigmoid function (yes=1 no=0)

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
#compile() method is a function of Sequential() class being called by its object 'ann'
#loss function is the method for calculating the errors-- always use binary_crossentropy for binary classification
#adam optimizer takes care of loss and fastens optimization(updates weights--backpropagate) by applying SGD algorithm 

### Training the ANN on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
#fit() method is a function of Sequential() class being called by its object 'ann'
#mini-batch gradient descent algorithm with b=32

Epoch 1/100
250/250 [==============================] - 0s 652us/step - loss: 0.5264 - accuracy: 0.7943
Epoch 2/100
250/250 [==============================] - 0s 583us/step - loss: 0.4742 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 602us/step - loss: 0.4505 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 650us/step - loss: 0.4373 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 626us/step - loss: 0.4305 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 550us/step - loss: 0.4262 - accuracy: 0.8050
Epoch 7/100
250/250 [==============================] - 0s 593us/step - loss: 0.4232 - accuracy: 0.8144
Epoch 8/100
250/250 [==============================] - 0s 622us/step - loss: 0.4205 - accuracy: 0.8198
Epoch 9/100
250/250 [==============================] - 0s 627us/step - loss: 0.4183 - accuracy: 0.8229
Epoch 10/100
250/250 [==============================] - 0s 611us/step - l

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [18]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)
#never forget to scale ie transform test set for neural networks

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [19]:
y_pred = ann.predict(X_test)
#predict() method is a function of Sequential() class being called by its object 'ann'
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))
#reshape pred and test vectors from horizontally to vertically for comparison using concatenate() function

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1505   90]
 [ 192  213]]


0.859